### PR TITLE
Update runtime to 5.15-22.08

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
might help fix some bugs related to mesa on some people's systems

### CODE REVIEW

**Comment by Etaash-mathamsetty** [comment]
bot, build com.moonlight_stream.Moonlight

**Comment by Etaash-mathamsetty** [comment]
works fine

**Comment by cgutman** [comment]
What Mesa-related issues did you see with the 5.15-21.08 runtime? I may just jump straight to the Qt 6.4 runtime once it's ready.

I'm seeing crashes here with 5.15-22.08 under Wayland on the Fedora 37 Beta:
```
Thread 1 "moonlight" received signal SIGSEGV, Segmentation fault.
0x00007fffbc008422 in QGnomePlatformDecoration::forceRepaint (this=0x555556281e40) at /run/build/qgnomeplatform-decoration/src/decoration/qgnomeplatformdecoration.cpp:660
660	/run/build/qgnomeplatform-decoration/src/decoration/qgnomeplatformdecoration.cpp: No such file or directory.
(gdb) bt
#0  0x00007fffbc008422 in QGnomePlatformDecoration::forceRepaint() (this=0x555556281e40) at /run/build/qgnomeplatform-decoration/src/decoration/qgnomeplatformdecoration.cpp:660
#1  0x00007fffbc0088af in QGnomePlatformDecoration::updateButtonHoverState(Button) (this=this@entry=0x555556281e40, hoveredButton=hoveredButton@entry=Close) at /run/build/qgnomeplatform-decoration/src/decoration/qgnomeplatformdecoration.cpp:809
#2  0x00007fffbc008b0d in QGnomePlatformDecoration::processMouseTop(QtWaylandClient::QWaylandInputDevice*, QPointF const&, QFlags<Qt::MouseButton>, QFlags<Qt::KeyboardModifier>) (this=0x555556281e40, inputDevice=0x555555a59580, local=..., b=..., mods=...)
    at /run/build/qgnomeplatform-decoration/src/decoration/qgnomeplatformdecoration.cpp:704
#3  0x00007fffbc00900e in QGnomePlatformDecoration::handleMouse(QtWaylandClient::QWaylandInputDevice*, QPointF const&, QPointF const&, QFlags<Qt::MouseButton>, QFlags<Qt::KeyboardModifier>)
    (this=0x555556281e40, inputDevice=0x555555a59580, local=..., global=<optimized out>, b=..., mods=...) at /run/build/qgnomeplatform-decoration/src/decoration/qgnomeplatformdecoration.cpp:563
#4  0x00007ffff16f9158 in QtWaylandClient::QWaylandWindow::handleMouseEventWithDecoration(QtWaylandClient::QWaylandInputDevice*, QtWaylandClient::QWaylandPointerEvent const&) () at /usr/lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
#5  0x00007ffff16f9540 in QtWaylandClient::QWaylandWindow::handleMouse(QtWaylandClient::QWaylandInputDevice*, QtWaylandClient::QWaylandPointerEvent const&) () at /usr/lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
#6  0x00007ffff16e97b3 in QtWaylandClient::QWaylandInputDevice::Pointer::flushFrameEvent() () at /usr/lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
#7  0x00007ffff4e4d056 in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.8
#8  0x00007ffff4e4b07b in ffi_call_int () at /usr/lib/x86_64-linux-gnu/libffi.so.8
#9  0x00007ffff76e8eee in wl_closure_invoke.constprop () at /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
#10 0x00007ffff76e96d3 in dispatch_event.isra () at /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
#11 0x00007ffff76e98bc in wl_display_dispatch_queue_pending () at /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
#12 0x00007ffff16ee9b2 in QtWaylandClient::QWaylandDisplay::flushRequests() () at /usr/lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
#13 0x00007ffff597b7ac in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff599bf15 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff594296b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff594aad6 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x000055555559d5bb in  ()
#18 0x00007ffff50a754a in __libc_start_call_main () at /usr/lib/x86_64-linux-gnu/libc.so.6
#19 0x00007ffff50a760b in __libc_start_main () at /usr/lib/x86_64-linux-gnu/libc.so.6
#20 0x000055555559e045 in  ()
```

I haven't had time to investigate the issue yet.

**Comment by Etaash-mathamsetty** [comment]
> What Mesa-related issues did you see with the 5.15-21.08 runtime? I may just jump straight to the Qt 6.4 runtime once it's ready.
> 
> I'm seeing crashes here with 5.15-22.08 under Wayland on the Fedora 37 Beta:
> 
> ```
> Thread 1 "moonlight" received signal SIGSEGV, Segmentation fault.
> 0x00007fffbc008422 in QGnomePlatformDecoration::forceRepaint (this=0x555556281e40) at /run/build/qgnomeplatform-decoration/src/decoration/qgnomeplatformdecoration.cpp:660
> 660	/run/build/qgnomeplatform-decoration/src/decoration/qgnomeplatformdecoration.cpp: No such file or directory.
> (gdb) bt
> #0  0x00007fffbc008422 in QGnomePlatformDecoration::forceRepaint() (this=0x555556281e40) at /run/build/qgnomeplatform-decoration/src/decoration/qgnomeplatformdecoration.cpp:660
> #1  0x00007fffbc0088af in QGnomePlatformDecoration::updateButtonHoverState(Button) (this=this@entry=0x555556281e40, hoveredButton=hoveredButton@entry=Close) at /run/build/qgnomeplatform-decoration/src/decoration/qgnomeplatformdecoration.cpp:809
> #2  0x00007fffbc008b0d in QGnomePlatformDecoration::processMouseTop(QtWaylandClient::QWaylandInputDevice*, QPointF const&, QFlags<Qt::MouseButton>, QFlags<Qt::KeyboardModifier>) (this=0x555556281e40, inputDevice=0x555555a59580, local=..., b=..., mods=...)
>     at /run/build/qgnomeplatform-decoration/src/decoration/qgnomeplatformdecoration.cpp:704
> #3  0x00007fffbc00900e in QGnomePlatformDecoration::handleMouse(QtWaylandClient::QWaylandInputDevice*, QPointF const&, QPointF const&, QFlags<Qt::MouseButton>, QFlags<Qt::KeyboardModifier>)
>     (this=0x555556281e40, inputDevice=0x555555a59580, local=..., global=<optimized out>, b=..., mods=...) at /run/build/qgnomeplatform-decoration/src/decoration/qgnomeplatformdecoration.cpp:563
> #4  0x00007ffff16f9158 in QtWaylandClient::QWaylandWindow::handleMouseEventWithDecoration(QtWaylandClient::QWaylandInputDevice*, QtWaylandClient::QWaylandPointerEvent const&) () at /usr/lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
> #5  0x00007ffff16f9540 in QtWaylandClient::QWaylandWindow::handleMouse(QtWaylandClient::QWaylandInputDevice*, QtWaylandClient::QWaylandPointerEvent const&) () at /usr/lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
> #6  0x00007ffff16e97b3 in QtWaylandClient::QWaylandInputDevice::Pointer::flushFrameEvent() () at /usr/lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
> #7  0x00007ffff4e4d056 in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.8
> #8  0x00007ffff4e4b07b in ffi_call_int () at /usr/lib/x86_64-linux-gnu/libffi.so.8
> #9  0x00007ffff76e8eee in wl_closure_invoke.constprop () at /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
> #10 0x00007ffff76e96d3 in dispatch_event.isra () at /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
> #11 0x00007ffff76e98bc in wl_display_dispatch_queue_pending () at /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
> #12 0x00007ffff16ee9b2 in QtWaylandClient::QWaylandDisplay::flushRequests() () at /usr/lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
> #13 0x00007ffff597b7ac in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
> #14 0x00007ffff599bf15 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
> #15 0x00007ffff594296b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
> #16 0x00007ffff594aad6 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
> #17 0x000055555559d5bb in  ()
> #18 0x00007ffff50a754a in __libc_start_call_main () at /usr/lib/x86_64-linux-gnu/libc.so.6
> #19 0x00007ffff50a760b in __libc_start_main () at /usr/lib/x86_64-linux-gnu/libc.so.6
> #20 0x000055555559e045 in  ()
> ```
> 
> I haven't had time to investigate the issue yet.

I wasn't having any mesa related issues, but others might have them, but yeah if moonlight supports qt 6, it will be better to move to that

**Pull request closed without merging**
